
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VIVOSHOP.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class ProductOrder
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ProductOrder()
    {

        this.Order_Parcel = "ไม่มีข้อมูล";

    }


        [DisplayName("เลขที่การขาย")]
        public int Order_Id { get; set; }
        [DisplayName("รหัสสมาชิก")]
        public int User_Id { get; set; }
        [DisplayName("วันที่การขาย")]
        public System.DateTime Order_Date { get; set; }
        [DisplayName("ยอดสุทธิ")]
        public decimal Order_Price { get; set; }
        [DisplayName("สถานะ")]
        public string Order_Status { get; set; }
        [DisplayName("หมายเลขพัสดุ")]
        public string Order_Parcel { get; set; }
        [DisplayName("สลิป")]

        public string Order_img { get; set; }

        [DisplayName("ที่อยู่ที่จัดส่ง")]
        public string Order_Address { get; set; }



    public virtual UserAccout UserAccout { get; set; }

}

}
