
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VIVOSHOP.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Product
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Product()
    {

        this.OrderDetails = new HashSet<OrderDetail>();

    }


        [DisplayName("รหัสสินค้า")]
        public int Pro_Id { get; set; }
        [DisplayName("ชื่อประเภทสินค้า")]
        public int ProType_Id { get; set; }
        [DisplayName("ชื่อสินค้า")]
        public string Pro_Name { get; set; }
        [DisplayName("รายละเอียดสินค้า")]
        public string Pro_Details { get; set; }
        [DisplayName("ราคาสินค้า")]
        public decimal Pro_Price { get; set; }
        [DisplayName("สี")]
        public string Pro_Color { get; set; }
        [DisplayName("รูปสินค้า")]
        public string Pro_Picture { get; set; }
        [DisplayName("รวมที่สั่งซื้อ")]

        public Nullable<int> Pro_Amout { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderDetail> OrderDetails { get; set; }

    public virtual ProductType ProductType { get; set; }

}

}
